//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KarmaEconomyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KarmaEconomyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoList.Model.KarmaEconomyResources", typeof(KarmaEconomyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string CompletionEasy {
            get {
                return ResourceManager.GetString("CompletionEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string CompletionHard {
            get {
                return ResourceManager.GetString("CompletionHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        internal static string CompletionImpossible {
            get {
                return ResourceManager.GetString("CompletionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string CompletionMedium {
            get {
                return ResourceManager.GetString("CompletionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string CompletionMustDo {
            get {
                return ResourceManager.GetString("CompletionMustDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CompletionMustDoRecurringBonus {
            get {
                return ResourceManager.GetString("CompletionMustDoRecurringBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string CompletionObligatoryRecurringBonus {
            get {
                return ResourceManager.GetString("CompletionObligatoryRecurringBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string CompletionVeryHard {
            get {
                return ResourceManager.GetString("CompletionVeryHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string CompletionVoluntaryRecurringBonus {
            get {
                return ResourceManager.GetString("CompletionVoluntaryRecurringBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -50.
        /// </summary>
        internal static string FailureMustDo {
            get {
                return ResourceManager.GetString("FailureMustDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -30.
        /// </summary>
        internal static string FailureObligatory {
            get {
                return ResourceManager.GetString("FailureObligatory", resourceCulture);
            }
        }
    }
}
